spring:
  application:
    name: jpa

  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: 7894
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true