spring:
  application:
    name: jobms

  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: postgres
    password: 7894
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache.use_second_level_cache: true
        cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

        # Enable Query Cache (Optional)
#        cache.use_query_cache: true


#  security:
#    user:
#      name: deepak
#      password: 1234

logging:
  level:
    root: info
    com.jobms.jobms: debug
    org.hibernate.cache.spi: debug

