spring:
  application:
    name: jobms

  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: postgres
    password: 7894
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    user:
#      name: deepak
#      password: 1234

logging:
  level:
    root: info
    com.jobms.jobms: debug

